#!/bin/bash

SRC_DIR=`pwd`
BUILD_DIR=${SRC_DIR}/build
mkdir -p ${BUILD_DIR} && cd ${BUILD_DIR}
#cmake -D CMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${PREFIX} -DTHREADS_PREFER_PTHREAD_FLAG=on ${SRC_DIR}
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${PREFIX} -DTHREADS_PREFER_PTHREAD_FLAG=on ${SRC_DIR}
make -j
make install


