package:
  name: lcm
  version: 1.3.1

source:
  git_url: https://github.com/lcm-proj/lcm
  git_branch: master
  # git_rev: 1.3.1

requirements:
  build:
    - python
    - pcre
    - cmake 
    - zlib
    - pkgconfig
    - autoconf
    - automake
  run:
    - python

tests:
  imports:
    - lcm

about:
  home: https://github.com/lcm-proj/lcm
  license: LGPL-3.0 
